name: Run Telegram Hadith Bot

on:
  schedule:
    - cron: "30 5 * * *"   # 12:30 WIB
    - cron: "0 11 * * *"   # 18:00 WIB
    - cron: "21 21 * * *"  # 04:00 WIB
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: |
          pip install requests gspread oauth2client python-dotenv

      - name: 🔐 Decode GOOGLE_CREDS_BASE64 to credentials.json
        run: echo "${{ secrets.GOOGLE_CREDS_BASE64 }}" | base64 -d > credentials.json

      - name: 🚀 Jalankan script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
